// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: eventresult.sql

package entities

import (
	"context"
)

const createEventResult = `-- name: CreateEventResult :one
INSERT INTO event_result (event_id, user_id, best_lap_time, average_lap_time, position, number_of_laps) VALUES (?, ?, ?, ?, ?, ?)
    RETURNING id, event_id, user_id, best_lap_time, average_lap_time, position, number_of_laps
`

type CreateEventResultParams struct {
	EventID        int64
	UserID         int64
	BestLapTime    int64
	AverageLapTime int64
	Position       int64
	NumberOfLaps   int64
}

func (q *Queries) CreateEventResult(ctx context.Context, arg CreateEventResultParams) (EventResult, error) {
	row := q.db.QueryRowContext(ctx, createEventResult,
		arg.EventID,
		arg.UserID,
		arg.BestLapTime,
		arg.AverageLapTime,
		arg.Position,
		arg.NumberOfLaps,
	)
	var i EventResult
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.BestLapTime,
		&i.AverageLapTime,
		&i.Position,
		&i.NumberOfLaps,
	)
	return i, err
}

const getEventResultByEventIdAndUserId = `-- name: GetEventResultByEventIdAndUserId :one
SELECT id, event_id, user_id, best_lap_time, average_lap_time, position, number_of_laps FROM event_result WHERE event_id = ? and user_id = ?
`

type GetEventResultByEventIdAndUserIdParams struct {
	EventID int64
	UserID  int64
}

func (q *Queries) GetEventResultByEventIdAndUserId(ctx context.Context, arg GetEventResultByEventIdAndUserIdParams) (EventResult, error) {
	row := q.db.QueryRowContext(ctx, getEventResultByEventIdAndUserId, arg.EventID, arg.UserID)
	var i EventResult
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.BestLapTime,
		&i.AverageLapTime,
		&i.Position,
		&i.NumberOfLaps,
	)
	return i, err
}

const getUserFriendsResults = `-- name: GetUserFriendsResults :many
SELECT event.id, event.location_id, event.type, event.date, event.total_drivers, location.id, location.name, event_result.id, event_result.event_id, event_result.user_id, event_result.best_lap_time, event_result.average_lap_time, event_result.position, event_result.number_of_laps, user.id, user.first_name, user.last_name, user.email, user.profile_id, user.display_name, user.created_at FROM event
    LEFT JOIN location ON event.location_id = location.id
    LEFT JOIN event_result ON event.id = event_result.event_id
    LEFT JOIN user ON user.id = event_result.user_id
    WHERE event_result.user_id in (SELECT friend_id FROM friend WHERE friend.user_id = ?)
`

type GetUserFriendsResultsRow struct {
	Event       Event
	Location    Location
	EventResult EventResult
	User        User
}

func (q *Queries) GetUserFriendsResults(ctx context.Context, userID int64) ([]GetUserFriendsResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserFriendsResults, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFriendsResultsRow
	for rows.Next() {
		var i GetUserFriendsResultsRow
		if err := rows.Scan(
			&i.Event.ID,
			&i.Event.LocationID,
			&i.Event.Type,
			&i.Event.Date,
			&i.Event.TotalDrivers,
			&i.Location.ID,
			&i.Location.Name,
			&i.EventResult.ID,
			&i.EventResult.EventID,
			&i.EventResult.UserID,
			&i.EventResult.BestLapTime,
			&i.EventResult.AverageLapTime,
			&i.EventResult.Position,
			&i.EventResult.NumberOfLaps,
			&i.User.ID,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.Email,
			&i.User.ProfileID,
			&i.User.DisplayName,
			&i.User.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
