// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event.sql

package entities

import (
	"context"
	"strings"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO event (location_id, type, date, total_drivers) VALUES (?, ?, ?, ?)
    RETURNING id, location_id, type, date, total_drivers
`

type CreateEventParams struct {
	LocationID   int64
	Type         string
	Date         string
	TotalDrivers int64
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.LocationID,
		arg.Type,
		arg.Date,
		arg.TotalDrivers,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Type,
		&i.Date,
		&i.TotalDrivers,
	)
	return i, err
}

const getEventByLocationAndTypeAndDate = `-- name: GetEventByLocationAndTypeAndDate :one
SELECT id, location_id, type, date, total_drivers FROM event WHERE location_id = ? AND type = ? AND date = ?
`

type GetEventByLocationAndTypeAndDateParams struct {
	LocationID int64
	Type       string
	Date       string
}

func (q *Queries) GetEventByLocationAndTypeAndDate(ctx context.Context, arg GetEventByLocationAndTypeAndDateParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByLocationAndTypeAndDate, arg.LocationID, arg.Type, arg.Date)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Type,
		&i.Date,
		&i.TotalDrivers,
	)
	return i, err
}

const getEventsByUser = `-- name: GetEventsByUser :many
SELECT event.id, event.location_id, event.type, event.date, event.total_drivers, location.id, location.name, event_result.id, event_result.event_id, event_result.user_id, event_result.best_lap_time, event_result.average_lap_time, event_result.position, event_result.number_of_laps, user.id, user.first_name, user.last_name, user.email, user.profile_id, user.display_name, user.created_at FROM event
    LEFT JOIN location on event.location_id = location.id
    LEFT JOIN event_result on event.id = event_result.event_id
    LEFT JOIN user on user.id = event_result.user_id
    WHERE event_result.user_id in (/*SLICE:ids*/?)
`

type GetEventsByUserRow struct {
	Event       Event
	Location    Location
	EventResult EventResult
	User        User
}

func (q *Queries) GetEventsByUser(ctx context.Context, ids []int64) ([]GetEventsByUserRow, error) {
	query := getEventsByUser
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsByUserRow
	for rows.Next() {
		var i GetEventsByUserRow
		if err := rows.Scan(
			&i.Event.ID,
			&i.Event.LocationID,
			&i.Event.Type,
			&i.Event.Date,
			&i.Event.TotalDrivers,
			&i.Location.ID,
			&i.Location.Name,
			&i.EventResult.ID,
			&i.EventResult.EventID,
			&i.EventResult.UserID,
			&i.EventResult.BestLapTime,
			&i.EventResult.AverageLapTime,
			&i.EventResult.Position,
			&i.EventResult.NumberOfLaps,
			&i.User.ID,
			&i.User.FirstName,
			&i.User.LastName,
			&i.User.Email,
			&i.User.ProfileID,
			&i.User.DisplayName,
			&i.User.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentEvents = `-- name: GetRecentEvents :many
SELECT event.id, event.location_id, event.type, event.date, event.total_drivers, event_result.id, event_result.event_id, event_result.user_id, event_result.best_lap_time, event_result.average_lap_time, event_result.position, event_result.number_of_laps, location.id, location.name
FROM event 
JOIN event_result on event.id = event_result.event_id
JOIN location on location.id = event.location_id
WHERE event_result.user_id = ?1
ORDER BY event.date DESC
LIMIT 10
`

type GetRecentEventsRow struct {
	Event       Event
	EventResult EventResult
	Location    Location
}

func (q *Queries) GetRecentEvents(ctx context.Context, userid int64) ([]GetRecentEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentEvents, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentEventsRow
	for rows.Next() {
		var i GetRecentEventsRow
		if err := rows.Scan(
			&i.Event.ID,
			&i.Event.LocationID,
			&i.Event.Type,
			&i.Event.Date,
			&i.Event.TotalDrivers,
			&i.EventResult.ID,
			&i.EventResult.EventID,
			&i.EventResult.UserID,
			&i.EventResult.BestLapTime,
			&i.EventResult.AverageLapTime,
			&i.EventResult.Position,
			&i.EventResult.NumberOfLaps,
			&i.Location.ID,
			&i.Location.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByLocationAndTypeAndDate = `-- name: ListEventsByLocationAndTypeAndDate :many
SELECT id, location_id, type, date, total_drivers FROM event
WHERE location_id = ? AND type = ? AND date = ?
ORDER BY id ASC
`

type ListEventsByLocationAndTypeAndDateParams struct {
	LocationID int64
	Type       string
	Date       string
}

func (q *Queries) ListEventsByLocationAndTypeAndDate(ctx context.Context, arg ListEventsByLocationAndTypeAndDateParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByLocationAndTypeAndDate, arg.LocationID, arg.Type, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Type,
			&i.Date,
			&i.TotalDrivers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
