// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friend.sql

package entities

import (
	"context"
)

const addFriend = `-- name: AddFriend :one
INSERT INTO friend (user_id, friend_id, friend_status) VALUES (?, ?, ?) RETURNING id, user_id, friend_id, friend_status, accepted_date, created_at, updated_at, row_version
`

type AddFriendParams struct {
	UserID       int64
	FriendID     int64
	FriendStatus string
}

func (q *Queries) AddFriend(ctx context.Context, arg AddFriendParams) (Friend, error) {
	row := q.db.QueryRowContext(ctx, addFriend, arg.UserID, arg.FriendID, arg.FriendStatus)
	var i Friend
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.FriendStatus,
		&i.AcceptedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const getFriendByUserIdAndFriendId = `-- name: GetFriendByUserIdAndFriendId :one
SELECT id, user_id, friend_id, friend_status, accepted_date, created_at, updated_at, row_version
FROM friend
WHERE 
    (friend_id = ?1 AND user_id = ?2)
    OR
    (user_id = ?1 AND friend_id = ?2)
LIMIT 1
`

type GetFriendByUserIdAndFriendIdParams struct {
	Userid   int64
	Friendid int64
}

func (q *Queries) GetFriendByUserIdAndFriendId(ctx context.Context, arg GetFriendByUserIdAndFriendIdParams) (Friend, error) {
	row := q.db.QueryRowContext(ctx, getFriendByUserIdAndFriendId, arg.Userid, arg.Friendid)
	var i Friend
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.FriendStatus,
		&i.AcceptedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}

const getFriendsByUser = `-- name: GetFriendsByUser :many
SELECT user.id, user.first_name, user.last_name, user.profile_id, user.display_name, COALESCE(friend.friend_status, 'NONE') AS friend_status,
        CASE 
            WHEN friend.friend_id = ?1 AND COALESCE(friend.friend_status, 'NONE') = 'REQUESTED' THEN 'true'
            ELSE 'false'
        END AS confirmation_required
    FROM user
    LEFT JOIN friend ON (user.id = friend.user_id OR user.id = friend.friend_id)
    WHERE user.id in (
        SELECT friend.user_id FROM friend WHERE friend.friend_id = ?1 AND friend_status != 'CANCELLED'
        UNION
        SELECT friend.friend_id FROM friend WHERE friend.user_id = ?1 AND friend_status != 'CANCELLED'
    ) AND user.id != ?1
`

type GetFriendsByUserRow struct {
	ID                   int64
	FirstName            string
	LastName             string
	ProfileID            string
	DisplayName          string
	FriendStatus         string
	ConfirmationRequired string
}

func (q *Queries) GetFriendsByUser(ctx context.Context, userid int64) ([]GetFriendsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFriendsByUser, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendsByUserRow
	for rows.Next() {
		var i GetFriendsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.ProfileID,
			&i.DisplayName,
			&i.FriendStatus,
			&i.ConfirmationRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFriendStatus = `-- name: UpdateFriendStatus :one
UPDATE friend SET friend_status = ? WHERE id = ? RETURNING id, user_id, friend_id, friend_status, accepted_date, created_at, updated_at, row_version
`

type UpdateFriendStatusParams struct {
	FriendStatus string
	ID           int64
}

func (q *Queries) UpdateFriendStatus(ctx context.Context, arg UpdateFriendStatusParams) (Friend, error) {
	row := q.db.QueryRowContext(ctx, updateFriendStatus, arg.FriendStatus, arg.ID)
	var i Friend
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FriendID,
		&i.FriendStatus,
		&i.AcceptedDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RowVersion,
	)
	return i, err
}
