// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: headtohead.sql

package entities

import (
	"context"
)

const getHeadToHead = `-- name: GetHeadToHead :many
SELECT
    friend_user.id,
    friend_user.first_name,
    friend_user.last_name,
    friend_user.display_name,
    CAST(COALESCE(SUM(CASE WHEN mine.position < theirs.position THEN 1 ELSE 0 END), 0) AS INTEGER) AS user_wins,
    CAST(COALESCE(SUM(CASE WHEN theirs.position < mine.position THEN 1 ELSE 0 END), 0) AS INTEGER) AS friend_wins,
    CAST(COUNT(*) AS INTEGER) AS shared_races
FROM event_result AS mine
JOIN event_result AS theirs
    ON theirs.event_id = mine.event_id
    AND theirs.user_id != mine.user_id
JOIN user AS friend_user
    ON friend_user.id = theirs.user_id
WHERE mine.user_id = ?1
    AND theirs.user_id IN (
        SELECT friend.friend_id
        FROM friend
        WHERE friend.user_id = ?1
            AND friend.friend_status = 'ACCEPTED'
        UNION
        SELECT friend.user_id
        FROM friend
        WHERE friend.friend_id = ?1
            AND friend.friend_status = 'ACCEPTED'
    )
GROUP BY friend_user.id, friend_user.first_name, friend_user.last_name, friend_user.display_name
ORDER BY shared_races DESC, friend_user.display_name COLLATE NOCASE ASC, friend_user.id ASC
`

type GetHeadToHeadRow struct {
	ID          int64
	FirstName   string
	LastName    string
	DisplayName string
	UserWins    int64
	FriendWins  int64
	SharedRaces int64
}

func (q *Queries) GetHeadToHead(ctx context.Context, userid int64) ([]GetHeadToHeadRow, error) {
	rows, err := q.db.QueryContext(ctx, getHeadToHead, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHeadToHeadRow
	for rows.Next() {
		var i GetHeadToHeadRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DisplayName,
			&i.UserWins,
			&i.FriendWins,
			&i.SharedRaces,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
