// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: location.sql

package entities

import (
	"context"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO location (name) VALUES (?)
    RETURNING id, name
`

func (q *Queries) CreateLocation(ctx context.Context, name string) (Location, error) {
	row := q.db.QueryRowContext(ctx, createLocation, name)
	var i Location
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getLocationByName = `-- name: GetLocationByName :one
SELECT id, name FROM location WHERE name = ?
`

func (q *Queries) GetLocationByName(ctx context.Context, name string) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocationByName, name)
	var i Location
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
