// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: magiclink.sql

package entities

import (
	"context"
)

const consumeMagicLink = `-- name: ConsumeMagicLink :execrows
UPDATE magic_link
SET used_at = CURRENT_TIMESTAMP
WHERE id = ? AND used_at IS NULL
`

func (q *Queries) ConsumeMagicLink(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeMagicLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createMagicLink = `-- name: CreateMagicLink :one
INSERT INTO magic_link (email, token_hash, purpose, expires_at)
VALUES (?, ?, ?, ?)
RETURNING id, email, token_hash, purpose, expires_at, used_at, created_at
`

type CreateMagicLinkParams struct {
	Email     string
	TokenHash string
	Purpose   string
	ExpiresAt string
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (MagicLink, error) {
	row := q.db.QueryRowContext(ctx, createMagicLink,
		arg.Email,
		arg.TokenHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveMagicLinkByTokenHash = `-- name: GetActiveMagicLinkByTokenHash :one
SELECT id, email, token_hash, purpose, expires_at, used_at, created_at
FROM magic_link
WHERE token_hash = ? AND used_at IS NULL AND expires_at > ?2
`

type GetActiveMagicLinkByTokenHashParams struct {
	TokenHash string
	Now       string
}

func (q *Queries) GetActiveMagicLinkByTokenHash(ctx context.Context, arg GetActiveMagicLinkByTokenHashParams) (MagicLink, error) {
	row := q.db.QueryRowContext(ctx, getActiveMagicLinkByTokenHash, arg.TokenHash, arg.Now)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TokenHash,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateUnusedMagicLinks = `-- name: InvalidateUnusedMagicLinks :exec
UPDATE magic_link
SET used_at = CURRENT_TIMESTAMP
WHERE email = ? AND used_at IS NULL
`

func (q *Queries) InvalidateUnusedMagicLinks(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, invalidateUnusedMagicLinks, email)
	return err
}
