// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package entities

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO user (first_name, last_name, email, profile_id, display_name) VALUES (?, ?, ?, ?, ?)
    RETURNING first_name, last_name, email, profile_id, display_name, created_at
`

type CreateUserParams struct {
	FirstName   string
	LastName    string
	Email       string
	ProfileID   string
	DisplayName string
}

type CreateUserRow struct {
	FirstName   string
	LastName    string
	Email       string
	ProfileID   string
	DisplayName string
	CreatedAt   sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.ProfileID,
		arg.DisplayName,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.ProfileID,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEventResultsByUserId = `-- name: DeleteEventResultsByUserId :exec
DELETE FROM event_result WHERE user_id = ?
`

func (q *Queries) DeleteEventResultsByUserId(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventResultsByUserId, userID)
	return err
}

const deleteFriendsByUserId = `-- name: DeleteFriendsByUserId :exec
DELETE FROM friend WHERE user_id = ?1 OR friend_id = ?1
`

func (q *Queries) DeleteFriendsByUserId(ctx context.Context, userid int64) error {
	_, err := q.db.ExecContext(ctx, deleteFriendsByUserId, userid)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM user WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email, profile_id FROM user WHERE email = ?
`

type GetUserByEmailRow struct {
	ID        int64
	FirstName string
	LastName  string
	Email     string
	ProfileID string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.ProfileID,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, first_name, last_name, email, profile_id, display_name, created_at FROM user WHERE id = ?
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.ProfileID,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserIdByProfileId = `-- name: GetUserIdByProfileId :one
SELECT user.id FROM user WHERE user.profile_id = ?
`

func (q *Queries) GetUserIdByProfileId(ctx context.Context, profileID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserIdByProfileId, profileID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUsersBySearchTerm = `-- name: GetUsersBySearchTerm :many
SELECT user.id, user.first_name, user.last_name, user.profile_id,
       CAST(COALESCE(
           (SELECT friend.friend_status
            FROM friend
            WHERE friend.friend_status != 'CANCELLED'
              AND (
                    (friend.user_id = ?1 AND friend.friend_id = user.id)
                    OR
                    (friend.friend_id = ?1 AND friend.user_id = user.id)
                  )
            LIMIT 1),
           'NONE'
       ) AS TEXT) AS friend_status
FROM user
WHERE CONCAT(LOWER(user.first_name), ' ', LOWER(user.last_name)) LIKE ?2
  AND user.id != ?1
`

type GetUsersBySearchTermParams struct {
	Userid int64
	Name   string
}

type GetUsersBySearchTermRow struct {
	ID           int64
	FirstName    string
	LastName     string
	ProfileID    string
	FriendStatus string
}

func (q *Queries) GetUsersBySearchTerm(ctx context.Context, arg GetUsersBySearchTermParams) ([]GetUsersBySearchTermRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersBySearchTerm, arg.Userid, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersBySearchTermRow
	for rows.Next() {
		var i GetUsersBySearchTermRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.ProfileID,
			&i.FriendStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE user SET first_name = ?, last_name = ?, email = ?, display_name = ? WHERE id = ?
`

type UpdateUserParams struct {
	FirstName   string
	LastName    string
	Email       string
	DisplayName string
	ID          int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.DisplayName,
		arg.ID,
	)
	return err
}
