// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Leaderboard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Head().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<body><div id=\"leaderboard-container\"><table id=\"leaderboard-table\"><thead><th class=\"leaderboard-header-cell\">Pos</th><th class=\"leaderboard-header-cell\">Driver</th><th class=\"leaderboard-header-cell\">Date</th><th class=\"leaderboard-header-cell\">Location</th><th class=\"leaderboard-header-cell\">Event Type</th><th class=\"leaderboard-header-cell\">Best Lap Time</th><th class=\"leaderboard-header-cell\">Average Lap Time</th><th class=\"leaderboard-header-cell\">Position</th><th class=\"leaderboard-header-cell\">Number Of Laps</th></thead> <tbody><tr class=\"leaderboard-row\"><td class=\"leaderboard-cell\">1</td><td class=\"leaderboard-cell\">Nick Stewart</td><td class=\"leaderboard-cell\">2025-09-12</td><td class=\"leaderboard-cell\">Daytona Milton Keynes</td><td class=\"leaderboard-cell\">SODI (2024 20min Race)</td><td class=\"leaderboard-cell\">1:10:05.12</td><td class=\"leaderboard-cell\">1:11:10.33</td><td class=\"leaderboard-cell\">10</td><td class=\"leaderboard-cell\">14</td></tr><tr class=\"leaderboard-row\"><td class=\"leaderboard-cell\">2</td><td class=\"leaderboard-cell\">Alex Adams</td><td class=\"leaderboard-cell\">2025-09-12</td><td class=\"leaderboard-cell\">Daytona Milton Keynes</td><td class=\"leaderboard-cell\">SODI (2024 20min Race)</td><td class=\"leaderboard-cell\">1:12:12.12</td><td class=\"leaderboard-cell\">1:14:53.33</td><td class=\"leaderboard-cell\">15</td><td class=\"leaderboard-cell\">14</td></tr></tbody></table></div></body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
